import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync, readdirSync } from "fs";
import { dirname, join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outfile = "dist/main.js";

// Ensure the output directory exists
const outDir = dirname(outfile);
if (!existsSync(outDir)) {
	mkdirSync(outDir, { recursive: true });
}

// Create prompts directory in dist
const promptsDir = `${outDir}/prompts`;
if (!existsSync(promptsDir)) {
	mkdirSync(promptsDir, { recursive: true });
}

// Copy manifest.json, styles.css, and prompt templates to dist
function copyFilesToDist() {
	// Copy manifest and styles
	copyFileSync("manifest.json", `${outDir}/manifest.json`);
	copyFileSync("styles.css", `${outDir}/styles.css`);
	console.log("Copied manifest.json and styles.css to dist directory");

	// Copy prompt templates
	const srcPromptsDir = "src/prompts";
	if (existsSync(srcPromptsDir)) {
		const promptFiles = readdirSync(srcPromptsDir).filter((file) =>
			file.endsWith(".md")
		);
		promptFiles.forEach((file) => {
			copyFileSync(join(srcPromptsDir, file), join(promptsDir, file));
		});
		console.log(
			`Copied ${promptFiles.length} prompt templates to dist/prompts directory`
		);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyFilesToDist();
	process.exit(0);
} else {
	await context.watch();
	copyFilesToDist();

	// Set up file watchers for manifest.json and styles.css
	console.log(
		"Watching for changes in manifest.json, styles.css, and prompt templates..."
	);
	context.watch({
		onRebuild(error) {
			if (error) {
				console.error("Watch build failed:", error);
			} else {
				copyFilesToDist();
				console.log("Build successful, files copied to dist");
			}
		},
	});
}
